
services:
  postgres:
    container_name: split_and_share_db
    image: postgis/postgis:15-3.3
    restart: always
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_DB=split_and_share
    ports:
      - "5122:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  app:
    container_name: project_split_and_share    
    build:
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    dns:
      - 8.8.8.8
    ports:
      - "8088:8080"